language: node_js
node_js:
 - "node"

 script: echo "Running tests against $(node -v)..."

after_success:
  - script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage